---
version: '2'

services:
  e2e-test-clickroad-zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: e2e-test-clickroad-zookeeper
    container_name: e2e-test-clickroad-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  e2e-test-clickroad-kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: e2e-test-clickroad-kafka
    container_name: e2e-test-clickroad-kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - e2e-test-clickroad-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'e2e-test-clickroad-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://e2e-test-clickroad-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
