version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
      - image: confluentinc/cp-zookeeper:5.3.0
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-kafka:5.3.0
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    steps:
      - checkout
      - run: npm ci
      - run: node_modules/.bin/flow check
      - run:
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: node_modules/.bin/jest --ci --testTimeout=60000 --coverage --maxWorkers=2 --reporters=default --reporters=jest-junit
      - run: npx codecov
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage

  build:
    docker:
      - image: circleci/node:lts
    environment:
      DOCKER_IMAGE: docker.pkg.github.com/dialogs/clickroad-server/clickroad-server
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - setup_remote_docker
      - run: docker build -t $DOCKER_IMAGE .
      - run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
      - run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$CIRCLE_BUILD_NUM
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin docker.pkg.github.com
      - run: docker push $DOCKER_IMAGE

  build/sbt:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: Get sbt binary
          command: |
            sudo apt update && sudo apt install -y curl
            sudo curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sudo rm sbt-$SBT_VERSION.deb
            sudo apt-get update
            sudo apt-get install -y sbt python-pip git
            sudo pip install awscli
            sudo apt-get clean && sudo apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: compile protobuf sources with scalapb
          command: |
            cd scala
            sbt clean compile
      - run:
          name: write sbt credentials
          command: |
            echo "realm=Sonatype Nexus Repository Manager" > ~/.sbt/.credentials
            echo "host=nexus.transmit.im" >> ~/.sbt/.credentials
            echo "user=$NEXUS_PUBLISHER_USER" >> ~/.sbt/.credentials
            echo "password=$NEXUS_PUBLISHER_PASS" >> ~/.sbt/.credentials
      - run:
          name: write m2 credentials
          command: |
            mkdir ~/.m2
            echo "realm=Sonatype Nexus Repository Manager" > ~/.m2/.credentials
            echo "host=nexus.transmit.im" >> ~/.m2/.credentials
            echo "user=$NEXUS_PUBLISHER_USER" >> ~/.m2/.credentials
            echo "password=$NEXUS_PUBLISHER_PASS" >> ~/.m2/.credentials
      - save_cache:
          key: sbt-cache
          paths:
            - '~/.ivy2/cache'
            - '~/.sbt'
            - '~/.m2'
      - run:
          name: publish artifact
          command: |
            cd scala
            sbt publish

workflows:
  version: 2
  test-build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build/sbt:
          requires:
            - build
          filters:
            branches:
              only:
                - master
